spring:
  application:
    name: benefits-enrollment
  datasource:
    url: jdbc:h2:mem:benefitsdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  repository:
    type: memory

springdoc:
  swagger-ui:
    path: /swagger-ui.html
